# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Karthikraj Duraisamy
tagline:          'Into Mobile Apps Development'
description:      'Android-Java-iOS'
baseurl:          /

author:
  name:           'Karthikraj Duraisamy'
  url:            https://about.me/karthikrajduraisamy

gems: [jekyll-seo-tag, jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0


# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Karthik's Development blog

# Your email if you want it to be linked on the contact page
author_email: raj.karthik777@gmail.com

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://karthikraj.net/

safe: true
